### PR TITLE
Css refactor

### PR DESCRIPTION
**Pull request by Quantum158**
## Type of Change(s)
`Delete any bullet that does not apply`

My changes:
 - Update HTML, CSS, Github meta, or scripts used to generate the site

### CODE REVIEW

**Comment by Quantum158** [comment]
@EPSWebPreview

**Comment by EPSWebPreview** [comment]
I am a bot that helps simplify the contribution process by creating and managing preview websites of unfinished and pending contributions.

Please type `@EPSWebPreview help` for more information on what you can tell me to do.

**Comment by EPSWebPreview** [comment]
I couldn't understand what you were trying to tell me to do.

Please type `@EPSWebPreview help` for a list of commands I respond to.

**Comment by Quantum158** [comment]
@EPSWebPreview help

**Comment by EPSWebPreview** [comment]
As you are the author of these changes, you can currently run the following commands in this thread:

`@EPSWebPreview create` <-- create a preview site for you changes

`@EPSWebPreview status` <-- check for and link to an active preview (if one exists for this thread)

<br>`@EPSWebPreview help` <-- resend this comment

**Comment by Quantum158** [comment]
@EPSWebPreview create

**Comment by EPSWebPreview** [comment]
Preview created!

Here's a link to it: http://epswebpreview.westus2.cloudapp.azure.com:40050

**Comment by Quantum158** [comment]
@EPSWebPreview help

**Comment by EPSWebPreview** [comment]
As you are the author of these changes, you can currently run the following commands in this thread:

`@EPSWebPreview delete` <-- close your preview site

`@EPSWebPreview status` <-- check for and link to an active preview (if one exists for this thread)

<br>`@EPSWebPreview help` <-- resend this comment

**Comment by Quantum158** [comment]
@EPSWebPreview status

**Comment by EPSWebPreview** [comment]
You have an active preview!

Here's a link to it: http://epswebpreview.westus2.cloudapp.azure.com:40050

**Comment by Quantum158** [comment]
@EPSWebPreview delete

**Comment by EPSWebPreview** [comment]
Deleted. Thanks for helping me to save resources!

**Pull request merged**
